package inf310.sa.diagnosticoenfermedades;

import java.util.LinkedList;
import javax.swing.JOptionPane;

/* @author Jhafeth */
public class Formulario extends javax.swing.JFrame {

    /**
     * Creates new form Formulario
     */
    ArbolB A;
    int posMayor;

    public Formulario() {
        initComponents();
        A = new ArbolB();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn1 = new javax.swing.JButton();
        btnEval1 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jta = new javax.swing.JTextArea();
        btnEval2 = new javax.swing.JButton();
        btnImprimir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btn1.setText("Primer Ronda");
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });

        btnEval1.setText("Evaluar");
        btnEval1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEval1ActionPerformed(evt);
            }
        });

        btn2.setText("Segunda Ronda");
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });

        jta.setColumns(20);
        jta.setRows(5);
        jScrollPane1.setViewportView(jta);

        btnEval2.setText("Evaluar");
        btnEval2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEval2ActionPerformed(evt);
            }
        });

        btnImprimir.setText("Imprimir Arbol");
        btnImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprimirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 484, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnEval1)
                    .addComponent(btn2)
                    .addComponent(btn1)
                    .addComponent(btnImprimir)
                    .addComponent(btnEval2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(btn1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEval1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEval2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 420, Short.MAX_VALUE)
                        .addComponent(btnImprimir))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
        // TODO add your handling code here:
        LinkedList<String> p = new LinkedList<>();
        LinkedList<String> e = new LinkedList<>();
        Datos.sintomasPrimerEtapa(e, p);
        int resp;
        for (int i = 0; i < p.size(); i++) {
            resp = JOptionPane.showConfirmDialog(null, p.get(i));
            if (JOptionPane.OK_OPTION == resp) {
                A.insertar(true, e.get(i));
            } else {
                A.insertar(false, e.get(i));
            }
        }
    }//GEN-LAST:event_btn1ActionPerformed

    private void btnImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimirActionPerformed
        // TODO add your handling code here:
        jta.setText("");
        A.imprimir(jta);
    }//GEN-LAST:event_btnImprimirActionPerformed

    private void btnEval1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEval1ActionPerformed
        // TODO add your handling code here:
        LinkedList<Enfermedad> enfermedades = new LinkedList<>();
        LinkedList<String> nombreEnf = new LinkedList<>();
        Datos.enfermedadesPrimerEtapa(enfermedades, nombreEnf);
        int a;
        int mayor = 0;
        posMayor = -1;
        jta.setText("");
        for (int i = 0; i < enfermedades.size(); i++) {
            a = A.valoracion(enfermedades.get(i));
            posMayor = (a > mayor) ? i : posMayor;
            mayor = (a > mayor) ? a : mayor;
            jta.append(nombreEnf.get(i) + " : " + a + '\n');
        }
        jta.append("Enfermedad probable: " + nombreEnf.get(posMayor) + " " + mayor + '\n');
    }//GEN-LAST:event_btnEval1ActionPerformed

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
        // TODO add your handling code here:
// TODO add your handling code here:
        LinkedList<String> p = new LinkedList<>();
        LinkedList<String> e = new LinkedList<>();
        switch (posMayor) {
            case 0:
                Datos.sintomasEnfermedadesRespiratorias(e, p);
                break;
            case 1:
                Datos.sintomasEnfermedadesCardiacas(e, p);
                break;
            case 2:
                Datos.sintomasEnfermedadesVirales(e, p);
                break;
            case 3:
                Datos.sintomasEnfermedadesInstetinales(e, p);
                break;
            case 4:
                Datos.sintomasEnfermedadesExternas(e, p);
                break;
            default:
        }
        int resp;
        for (int i = 0; i < p.size(); i++) {
            resp = JOptionPane.showConfirmDialog(null, p.get(i));
            if (JOptionPane.OK_OPTION == resp) {
                A.insertar(true, e.get(i));
            } else {
                A.insertar(false, e.get(i));
            }
        }
    }//GEN-LAST:event_btn2ActionPerformed

    private void btnEval2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEval2ActionPerformed
        // TODO add your handling code here:
        LinkedList<Enfermedad> enfermedades = new LinkedList<>();
        LinkedList<String> nombreEnf = new LinkedList<>();
        switch (posMayor) {
            case 0:
                Datos.enfermedadesRespiratorias(enfermedades, nombreEnf);
                break;
            case 1:
                Datos.enfermedadesCardiacas(enfermedades, nombreEnf);
                break;
            case 2:
                Datos.enfermedadesVirales(enfermedades, nombreEnf);
                break;
            case 3:
                Datos.enfermedadesIntestinales(enfermedades, nombreEnf);
                break;
            case 4:
                Datos.enfermedadesExternas(enfermedades, nombreEnf);
                break;
            default:
        }
        int a;
        int mayor = 0;
        posMayor = -1;
        jta.append("------------------------" + '\n');
        for (int i = 0; i < enfermedades.size(); i++) {
            a = A.valoracion(enfermedades.get(i));
            posMayor = (a > mayor) ? i : posMayor;
            mayor = (a > mayor) ? a : mayor;
            jta.append(nombreEnf.get(i) + " : " + a + '\n');
        }
        jta.append("Enfermedad probable: " + nombreEnf.get(posMayor) + " " + mayor + '\n');
    }//GEN-LAST:event_btnEval2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Formulario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btnEval1;
    private javax.swing.JButton btnEval2;
    private javax.swing.JButton btnImprimir;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jta;
    // End of variables declaration//GEN-END:variables
}
