package inf310.sa.diagnosticoenfermedades;

import java.util.LinkedList;
import javax.swing.JOptionPane;

/**
 *
 * @author Jhafeth
 */
public class Presentacion extends javax.swing.JFrame {

    ArbolB A;
    LinkedList<Enfermedad> enfermedades;
    LinkedList<String> nombreEnf;

    public Presentacion() {
        initComponents();
        A = new ArbolB();
        enfermedades = new LinkedList<>();
        nombreEnf = new LinkedList<>();
        llenarEnfermedades();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSi = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jta = new javax.swing.JTextArea();
        btnNo = new javax.swing.JButton();
        t1 = new javax.swing.JTextField();
        btnImprimir = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnSi.setText("SI");
        btnSi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiActionPerformed(evt);
            }
        });

        jta.setColumns(20);
        jta.setRows(5);
        jScrollPane1.setViewportView(jta);

        btnNo.setText("NO");
        btnNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNoActionPerformed(evt);
            }
        });

        btnImprimir.setText("Imprimir");
        btnImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprimirActionPerformed(evt);
            }
        });

        jButton1.setText("Preguntar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Evaluar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 489, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(t1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSi)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnNo))
                    .addComponent(btnImprimir)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jButton2)
                        .addComponent(jButton1)))
                .addContainerGap(124, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(t1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSi)
                            .addComponent(btnNo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnImprimir)
                        .addGap(38, 38, 38)
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(232, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiActionPerformed
        // TODO add your handling code here:
        String nombre = t1.getText();
        A.insertar(true, nombre);
        t1.setText("");
    }//GEN-LAST:event_btnSiActionPerformed

    private void btnNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNoActionPerformed
        // TODO add your handling code here:
        String nombre = t1.getText();
        A.insertar(false, nombre);
        t1.setText("");
    }//GEN-LAST:event_btnNoActionPerformed

    private void btnImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimirActionPerformed
        // TODO add your handling code here:
        jta.setText("");
        A.imprimir(jta);
    }//GEN-LAST:event_btnImprimirActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        LinkedList<String> e = new LinkedList<>();

//sintomas base de datos
//manejo con listas

//sintomas de la segunda ronda
        e.add("DOLOR-PECHO");
        e.add("CUESTA-RESPIRAR");
        e.add("SILBIDO-RESPIRAR");
        e.add("HINCHAZON-ARTICULACION");
        e.add("LATIDOS-ACELERADOS");
        e.add("ERUPCION-CUTANEA");
        e.add("DOLOR-CABEZA");
        e.add("FIEBRE");
        e.add("FALTA-APETITO");
        e.add("LLENURA");
        e.add("DOLOR-ABDOMINAL");
        e.add("PICAZON-PIEL");
        e.add("PIEL-SECA");
        e.add("ARDOR-OJOS");
        e.add("LAGANAS");
        int resp;
        String nombre;
        for (int i = 0; i < e.size(); i++) {
            nombre = e.get(i);
            resp = JOptionPane.showConfirmDialog(null, "Usted presenta " + nombre + " ?");
            if (JOptionPane.OK_OPTION == resp) {
                A.insertar(true, nombre);
            } else {
                A.insertar(false, nombre);
            }
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        int a;
        jta.setText("");
        for (int i = 0; i < enfermedades.size(); i++) {
            a = A.valoracion(enfermedades.get(i));
            jta.append(nombreEnf.get(i) + " : " + a + '\n');
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Presentacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Presentacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Presentacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Presentacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Presentacion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnImprimir;
    private javax.swing.JButton btnNo;
    private javax.swing.JButton btnSi;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jta;
    private javax.swing.JTextField t1;
    // End of variables declaration//GEN-END:variables

    private void llenarEnfermedades() {
        Enfermedad e = new Enfermedad();
//enfermedades respiratorias: rinitis asma neumonia faringitis resfrio
        e.addSintoma("DOLOR-PECHO", 2);
        e.addSintoma("CUESTA-RESPIRAR", 3);
        e.addSintoma("SILBIDO-RESPIRAR", 5);
        enfermedades.add(e);
        nombreEnf.add("Enfermedades Respiratorias");
//enfermedades cardiacas: insuficiencia hipertension colesterol-alto
        e = new Enfermedad();
        e.addSintoma("HINCHAZON-ARTICULACION", 2);
        e.addSintoma("DOLOR-PECHO", 3);
        e.addSintoma("LATIDOS-ACELERADOS", 5);
        enfermedades.add(e);
        nombreEnf.add("Enfermedades Cardiacas");
//enfermedades virales: covid dengue mayaro fiebre-amarilla chikungunha
        e = new Enfermedad();
        e.addSintoma("ERUPCION-CUTANEA", 2);
        e.addSintoma("DOLOR-CABEZA", 3);
        e.addSintoma("FIEBRE", 5);
        enfermedades.add(e);
        nombreEnf.add("Enfermedades Virales");
//enfermedades intestinales: gastritis salmonela hepatitis inflamacion-intestinal
        e = new Enfermedad();
        e.addSintoma("FALTA-APETITO", 2);
        e.addSintoma("LLENURA", 3);
        e.addSintoma("DOLOR-ABDOMINAL", 4);
        enfermedades.add(e);
        nombreEnf.add("Enfermedades Intestinales");
//enfermedades externas: dermatitis pie-atleta conjuntivitis
        e = new Enfermedad();
        e.addSintoma("PICAZON-PIEL", 2);
        e.addSintoma("PIEL-SECA", 3);
        e.addSintoma("ARDOR-OJOS", 3);
        e.addSintoma("LAGANAS", 3);
        enfermedades.add(e);
        nombreEnf.add("Enfermedades Externas");

    }
/*enfermedades respiratorias: 
rinitis 
asma 
neumonia 
faringitis 
resfrio*/

/*enfermedades cardiacas: 
insuficiencia 
hipertension 
colesterol-alto*/

}
